### Creating and Checking No. Element ,Shape and Dimension of Array

In [7]:
import numpy as np

#### ONE DIMENTIONAL ARRAY

In [46]:
arr_1 = np.array([1,2,3,4,5,6,7])
arr_1

array([1, 2, 3, 4, 5, 6, 7])

#### TWO DIMENTIONAL ARRAY

In [48]:
arr_2 = np.array([[1,2,3],[1,2,3],[1,2,3]])
arr_2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

#### THREE DIMENTIONAL ARRAY

In [50]:
 arr_3 = np.array([
     [
         [1,2,3],
         [1,2,3],
         [1,2,3]
     ],
     [
         [1,2,3],
         [1,2,3],
         [1,2,3]
     ]   
 ])
arr_3

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

#### Total Element in Array

In [39]:
print("Size of Array 1 :: ",arr_1.size)  
print("Size of Array 2 :: ",arr_2.size)   
print("Size of Array 3 :: ",arr_3.size)   

Size of Array 1 ::  7
Size of Array 2 ::  9
Size of Array 3 ::  18


 #### Shape of Array

In [43]:
print("Shape of Array 1 ::",arr_1.shape)
print("Shape of Array 2 ::",arr_2.shape)
print("Shape of Array 3 ::",arr_3.shape)

Shape of Array 1 :: (7,)
Shape of Array 2 :: (3, 3)
Shape of Array 3 :: (2, 3, 3)


#### Dimension of Array

In [61]:
print("Dimension of Array 1 ::",arr_1.ndim)
print("Dimension of Array 2 ::",arr_2.ndim)
print("Dimension of Array 3 ::",arr_3.ndim)

Dimension of Array 1 :: 1
Dimension of Array 2 :: 2
Dimension of Array 3 :: 3
