In [1]:
import numpy as np

#### CREATING EMPTY ARRAY

In [3]:
arr1 = np.empty((3,3),dtype = int)   
arr1

array([[ 2103705600, -1805345948,   962921116],
       [    3971940, -2140930048, -1805345692],
       [  962921116,     3972196, -2107375616]])

#### CREATING ARRAY WITH ONES

In [5]:
arr2 = np.ones((3,3),dtype = int)  
arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#### CREATING ARRAY WITH ZEROS

In [7]:
arr3 = np.zeros((3,3))    
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

 #### CONVERTING ARRAY INTO BOOLEAN FORM

In [9]:
arr4 = np.ones((3,3),dtype = bool)  
arr4

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### CONERTING ARRAY INTO STRING FORM

In [11]:
arr5 =  np.ones((3,3),dtype = str)   
arr5

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')