### NumPy Array Concatenation and Split 

In [1]:
import numpy as np

#### Numpy arange() and reshape()

In [6]:
arr1 = np.arange(1,21).reshape(4,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [10]:
arr2 = np.arange(1,21).reshape(4,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

#### join two array

In [15]:
arr3 = np. concatenate((arr1,arr2))
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [21]:
arr3 = np. concatenate((arr1,arr2),axis= 1) # AXIS , 1 = ROW
arr3


array([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 16, 17, 18, 19, 20]])

#### JOIN TWO ARRAY BY STACK

In [26]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [28]:
np.hstack((arr1,arr2))


array([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 16, 17, 18, 19, 20]])

#### SPLIT ARRAY

In [35]:
split_arr1 = np.split(arr1,2)
split_arr1 

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])]

#### ACCESS THE SPLIT ARRAY

In [42]:
split_arr1[0]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [50]:
sp_split_arr1 = np.split(split_arr1[0],2)
sp_split_arr1

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]

In [52]:
sp_split_arr1[0]

array([[1, 2, 3, 4, 5]])

#### SPLIT 1 DIMENTIONAL ARRAY

In [80]:
arr_1D = np.arange(10)
arr_1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
np.split(arr_1D,(2))

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]