### Numpy Mathematical Functions

In [4]:
import numpy as np

#### APPLY MATHS OPERATION ON ARRAY

In [6]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)

#### Addition

In [8]:
arr_add = np.add(arr1,arr2) 
arr_add

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

#### Subtraction

In [10]:
arr_sub = np.subtract(arr1,arr2)
arr_sub

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

#### Multiplication

In [12]:
arr_mul = np.multiply(arr1,arr2,arr1)
arr_mul

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

#### Division

In [14]:
arr_div = np.divide(arr1,arr2)
arr_div

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

#### Modulo

In [16]:
arr_mod = np.mod(arr1,arr2)
arr_mod

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
arr_dot = np.dot(arr1,arr2)   
arr_dot

array([[1120, 1194, 1268],
       [3298, 3525, 3752],
       [6232, 6666, 7100]])

In [43]:
print("Sum of Array ::",np.sum(arr1))
print("Max Element in Array ::",np.max(arr1))
print("Max Element in Array ::",np.max(arr1))
print("index of max Element ::",np.argmax(arr1))
print("index of min Element ::",np.argmin(arr1))
print("Standart deviation of Array ::",np.std(arr1))
print("Mean of Array ::",np.mean(arr1))


Sum of Array :: 735
Max Element in Array :: 171
Max Element in Array :: 171
index of max Element :: 8
index of min Element :: 0
Standart deviation of Array :: 51.97007686052512
Mean of Array :: 81.66666666666667


In [39]:
np.sqrt(arr1)

array([[ 3.31662479,  4.89897949,  6.244998  ],
       [ 7.48331477,  8.66025404,  9.79795897],
       [10.90871211, 12.        , 13.07669683]])

In [20]:
np.exp(arr1)

array([[5.98741417e+04, 2.64891221e+10, 8.65934004e+16],
       [2.09165950e+24, 3.73324200e+32, 4.92345829e+41],
       [4.79781333e+51, 3.45466066e+62, 1.83804612e+74]])