## Numpy Array Broadcasting 
    Broadcasting allows NumPy to perform operations on arrays of different shapes by 
    treating them as if they have the same dimensions.

In [5]:
import numpy as np 

### Normalizing a Dataset (Matrix - Vector)

In [31]:
data = np.array([[10, 20, 30], 
                 [40, 50, 60], 
                 [70, 80, 90]])

# 1D array representing the mean of each column
col_means = data.mean(axis=0)

# Subtracting the 1D mean from the 2D matrix
# NumPy "stretches" col_means across all rows
normalized_data = data - col_means
print("Before Normalizing a Dataset ::\n",data)
print("After Normalizing a Dataset ::\n",normalized_data)

Before Normalizing a Dataset ::
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
After Normalizing a Dataset ::
 [[-30. -30. -30.]
 [  0.   0.   0.]
 [ 30.  30.  30.]]


### Scaling Rows (Matrix * Vector)

In [27]:
matrix = np.ones((3, 3))
scaling_factors = np.array([[10], [20], [30]]) 

# The column vector (3, 1) is broadcast across the columns of the matrix (3, 3)
scaled_matrix = matrix * scaling_factors
print("Before Sacling Rows ::\n",matrix)
print("After Sacling Rows ::\n",scaled_matrix)

Before Sacling Rows ::
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
After Sacling Rows ::
 [[10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
