## Indexing with Boolean Masks
    Boolean masking is used to select data that meets specific criteria.

In [2]:
import numpy as np 

### Finding and Replacing Outliers

In [30]:
# Suppose you have experimental data and want to cap any values that exceed a certain threshold.
# Create a 10x10 array of values from 1 to 100
arr_1 = np.arange(1, 101).reshape(10, 10)
arr = np.arange(1, 101).reshape(10, 10)
# 1. Create a mask for values greater than 85
mask = arr > 85

# 2. Extract those values
outliers = arr[mask] 

# 3. Replace those values in the original array
# Every number originally > 85 is now exactly 85
arr[mask] = 85 

print("Outliers ::",outliers)
print("Before Replacing Outliers ::\n ",arr_1)
print("After Replacing Outliers ::\n ",arr)

Outliers :: [ 86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]
Before Replacing Outliers ::
  [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
After Replacing Outliers ::
  [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]
 [71 72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 85 85 85 85 85]
 [85 85 85 85 85 85 85 85 85 85]]


### Filtering Rows Based on Column Conditions

In [16]:
# Data representing [ID, Score, Age]
students = np.array([
    [101, 85, 20],
    [102, 42, 21],
    [103, 90, 19],
    [104, 55, 22]
])

# Get a mask where the 'Score' (index 1) is less than 50
fail_mask = students[:, 1] < 50

# Select the rows (students) who failed
failing_students = students[fail_mask]
print("Students Data ::\n",students)
print("Students Who score less than 50 ::\n",failing_students)

Students Data ::
 [[101  85  20]
 [102  42  21]
 [103  90  19]
 [104  55  22]]
Students Who score less than 50 ::
 [[102  42  21]]


### Multiple Logical Conditions

In [23]:
values = np.array([10, 25, 40, 55, 70])

# Mask for values between 20 AND 60
combined_mask = (values > 20) & (values < 60)

filtered_values = values[combined_mask]
print("Values Before mask ::\n",values)
print("Filtered values [Values between 20 and 60 ] ::\n",filtered_values)

Values Before mask ::
 [10 25 40 55 70]
Filtered values [Values between 20 and 60 ] ::
 [25 40 55]
